-- SQL SCRIPT TO CREATE TABLES FOR
-- DANGLING MARKUP EXPLOIT

CREATE TABLE dm (
    iddm INT AUTO_INCREMENT PRIMARY KEY,
    comment VARCHAR(255)
);

CREATE TABLE i (
    idi INT AUTO_INCREMENT PRIMARY KEY,
    src VARCHAR(255)
);